#!/usr/bin/env node
/**
 * Emits the SQL that creates the schema and loads the demo dataset into D1.
 *
 * It writes a file rather than talking to Cloudflare directly, so the same output can be
 * applied locally or remotely:
 *
 *   node scripts/seed-db.mjs                        # writes dist/seed.sql
 *   npx wrangler d1 execute retail-price-intelligence --local  --file=dist/seed.sql
 *   npx wrangler d1 execute retail-price-intelligence --remote --file=dist/seed.sql
 *
 * Loading is idempotent: every row is an INSERT OR REPLACE keyed by id, and the script
 * clears the tables first, so re-running it restores the dataset exactly.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { buildSeedData } from '../public/app/seed.js';
import { TABLE_NAMES, columnNames, ddlStatements, toRow } from '../shared/schema.js';

const OUT = resolve(process.argv[2] ?? 'dist/seed.sql');
/** Fixed reference date so the dataset is reproducible across runs. */
const NOW = process.env.SEED_NOW ?? new Date().toISOString();

const data = buildSeedData(NOW);

// Opportunity lifecycle state is keyed by id in the client; store it as rows.
const rowsFor = (table) => {
  if (table === 'opportunity_states') {
    return Object.entries(data.opportunity_states ?? {}).map(([id, state]) => ({ id, ...state }));
  }
  return data[table] ?? [];
};

function quote(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

const lines = [
  '-- Generated by scripts/seed-db.mjs — do not edit by hand.',
  `-- Dataset reference date: ${NOW}`,
  'PRAGMA foreign_keys = OFF;',
  ...ddlStatements().map((s) => `${s};`),
];

let total = 0;
for (const table of TABLE_NAMES) {
  const rows = rowsFor(table);
  lines.push(`DELETE FROM ${table};`);
  if (!rows.length) continue;

  const cols = columnNames(table);
  // Batched multi-row inserts keep the statement count (and the file) manageable.
  for (let i = 0; i < rows.length; i += 100) {
    const chunk = rows.slice(i, i + 100);
    const values = chunk.map((row) => `(${toRow(table, row).map(quote).join(', ')})`).join(',\n  ');
    lines.push(`INSERT OR REPLACE INTO ${table} (${cols.join(', ')}) VALUES\n  ${values};`);
  }
  total += rows.length;
  console.log(`${table.padEnd(22)} ${rows.length} rows`);
}

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, `${lines.join('\n')}\n`, 'utf8');
console.log(`\n${total} rows across ${TABLE_NAMES.length} tables → ${OUT}`);
